project_id = "zbctynfnnrlhpatoateb"

[functions.image-editor]
verify_jwt = false

[functions.analyze-product]
verify_jwt = false

[functions.image-to-video]
verify_jwt = false

[functions.kie-veo-generate]
verify_jwt = false

[functions.kie-veo-status]
verify_jwt = false

[functions.kie-runway-generate]
verify_jwt = false

[functions.kie-runway-status]
verify_jwt = false

[functions.lemonsqueezy-payment]
verify_jwt = false

[functions.generate-video-prompts]
verify_jwt = false
