// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbctynfnnrlhpatoateb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiY3R5bmZubnJsaHBhdG9hdGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTI2ODcsImV4cCI6MjA2NTM4ODY4N30.uicxsnT24TknjeLYRH-1bOhxF9mfy9m_xvebYx1itHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);